<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHRYn3I3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHRYn3I3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHRYn3I3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHRYn3I3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHRYn3I3\App_KernelDevDebugContainer([
    'container.build_hash' => 'HRYn3I3',
    'container.build_id' => 'c7e23f80',
    'container.build_time' => 1612880659,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHRYn3I3');
