<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'root' => [[], ['_controller' => 'App\\Controller\\ApiController::root'], [], [['text', '/']], [], []],
    'api_qrcode_error' => [[], ['_controller' => 'App\\Controller\\ApiController::GetQrCode'], [], [['text', '/api/qrcode']], [], []],
    'api_scan_qrcode' => [['idQrCode'], ['_controller' => 'App\\Controller\\ApiController::GetQrCode'], [], [['variable', '', '[^/]++', 'idQrCode', true], ['text', '/api/qrcode?']], [], []],
    'api_myqrcodes' => [[], ['_controller' => 'App\\Controller\\ApiController::GetMyQrCodes'], [], [['text', '/api/my-qrcodes']], [], []],
    'api_promotions_qrcode' => [[], ['_controller' => 'App\\Controller\\ApiController::GetPromotions'], [], [['text', '/api/promotions']], [], []],
    'api_create_qrcode' => [['test'], ['_controller' => 'App\\Controller\\ApiController::CreateQrCode'], [], [['variable', '/', '[^/]++', 'test', true], ['text', '/api/create-qrcode']], [], []],
];
